"""Constants for GitHub Stats Card rendering and configuration."""

import os

# API Configuration
# Support GitHub Enterprise Server and other platforms via environment variables
# Fallback to github.com if not set
API_BASE_URL = os.environ.get("GITHUB_API_URL", "https://api.github.com")
GRAPHQL_ENDPOINT = os.environ.get("GITHUB_GRAPHQL_URL", f"{API_BASE_URL}/graphql")
API_TIMEOUT = 30

# Card Dimensions
CARD_PADDING = 25
DEFAULT_CARD_WIDTH = 495
DEFAULT_LANGS_CARD_WIDTH = 300
DEFAULT_LANGS_COMPACT_WIDTH = 467
MIN_CARD_WIDTH = 280
DEFAULT_BORDER_RADIUS = 4.5

# User Stats Card Layout
STAT_LINE_HEIGHT = 25
DEFAULT_LINE_HEIGHT = 25
USER_STATS_CARD_BASE_HEIGHT = 40
RANK_CIRCLE_RADIUS = 40
RANK_CIRCLE_X_OFFSET = 390.5
RANK_CIRCLE_Y_OFFSET = 47.5
STAT_VALUE_X_POSITION = 219.01
STAT_LABEL_X_BASE = 0
STAT_LABEL_X_WITH_ICON = 25

# Languages Card Layout
MAXIMUM_LANGS_COUNT = 20
LANGS_PROGRESS_BAR_HEIGHT = 8
LANGS_LEGEND_CIRCLE_RADIUS = 5
LANGS_COMPACT_COLUMN_WIDTH = 150
LANGS_COMPACT_COLUMN_WIDTH_WIDE = 225  # For 467px width compact layout
LANGS_COMPACT_ROW_HEIGHT = 25
LANGS_DONUT_RADIUS = 40
LANGS_DONUT_STROKE_WIDTH = 25
LANGS_PIE_RADIUS = 90

# Animation Settings
ANIMATION_INITIAL_DELAY_MS = 450
ANIMATION_STAGGER_DELAY_MS = 150
ANIMATION_FADE_DURATION_MS = 300
ANIMATION_SCALE_DURATION_MS = 300
ANIMATION_GROW_WIDTH_DURATION_MS = 600

# Color Settings
DEFAULT_LANG_COLOR = "#858585"

# Rank Calculation
RANK_S_THRESHOLD = 0.01
RANK_A_PLUS_THRESHOLD = 0.25
RANK_A_THRESHOLD = 0.45
RANK_A_MINUS_THRESHOLD = 0.60
RANK_B_PLUS_THRESHOLD = 0.70
RANK_B_THRESHOLD = 0.80
RANK_B_MINUS_THRESHOLD = 0.90
RANK_C_PLUS_THRESHOLD = 1.00

# Font Settings
FONT_FAMILY_HEADER = "'Segoe UI', Ubuntu, Sans-Serif"
FONT_FAMILY_STAT = "'Segoe UI', Ubuntu, 'Helvetica Neue', Sans-Serif"
FONT_FAMILY_LANG = "'Segoe UI', Ubuntu, Sans-Serif"
FONT_SIZE_HEADER = 18
FONT_SIZE_STAT = 14
FONT_SIZE_LANG = 11
FONT_SIZE_RANK = 24
FONT_WEIGHT_HEADER = 600
FONT_WEIGHT_STAT = 600
FONT_WEIGHT_STAT_BOLD = 700
FONT_WEIGHT_RANK = 800

# Number Formatting
NUMBER_FORMAT_SHORT = "short"
NUMBER_FORMAT_LONG = "long"
NUMBER_FORMAT_THOUSAND_DIVISOR = 1000
